export const ADD_ERROR = "ADD_ERROR"
export const REMOVE_ERROR = "REMOVE_ERROR"
export const SET_DATE = "SET_DATE"
export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const LOADING = "LOADING"
export const LOAD_HOUSES = "LOAD_HOUSES"
export const DELETE_HOUSE = "DELETE_HOUSE"